inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'script/*'
    - 'vendor/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'spec/**/*'
    - 'Guardfile'

Metrics/LineLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'features/support/env.rb'
    - 'lib/tasks/cucumber.rake'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

RSpec/NestedGroups:
  Max: 6

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%w': '()'
    '%W': '()'
